# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZC6D35Gmf1m2y0MnS4CZZ7OYwgtovsfL
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import joblib

data = pd.DataFrame({
    "monthly_spend": [50, 60, 70, 120, 150, 200, 80, 90, 40, 30],
    "tenure_months": [2, 3, 6, 12, 24, 36, 4, 5, 1, 1],
    "support_calls": [3, 1, 0, 1, 0, 0, 2, 1, 4, 3],
    "churn": [1, 1, 0, 0, 0, 0, 1, 0, 1, 1]
})

# Prepare features and target
X = data[["monthly_spend", "tenure_months", "support_calls"]]
y = data["churn"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#  Train the model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)


# IN PRACTICE (or final projects), create the best performing model you can
# (balancing bias-variance) using all your skills.

# --- NEW STEP: Save the trained model to a file ---
# --- This is the DEPLOYED model ---

#  Save the trained model
joblib.dump(model, "churn_model.pkl")
print("Model saved as churn_model.pkl")

!ls

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# 
# from fastapi import FastAPI
# import joblib
# import numpy as np
# 
# # --- Create the API application ---
# app = FastAPI(title="Churn Prediction API")
# 
# # --- Load the saved model (from the .pkl file) ---
# model = joblib.load("churn_model.pkl")
# 
# # --- Endpoint 1: Home page (just confirms the API is alive) ---
# @app.get("/")
# def home():
#     return {"message": "Churn Prediction API is running"}
# 
# # --- Endpoint 2: Prediction (this is the one that does the work) ---
# @app.post("/predict")
# def predict(data: dict):
#     # Pull the customer's features out of the incoming request
#     features = np.array([[
#         data["monthly_spend"],
#         data["tenure_months"],
#         data["support_calls"]
#     ]])
# 
#     # Use the model to get a churn probability
#     churn_prob = model.predict_proba(features)[0][1]
# 
#     return {
#         "churn_probability": round(float(churn_prob), 4)
#     }
#

!ls

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# fastapi
# uvicorn
# scikit-learn
# joblib
# numpy
# pandas
#

!ls